---
name: Markdown Lint
description: A Buildkite plugin to check Markdown files and flag style issues.
author: https://msha.ke/johnsyweb/
requirements:
  - docker
configuration:
  properties:
    pattern:
      type: string
    version:
      type: string
