---
name: Markdown Lint
description: A Buildkite plugin to check Markdown files and flag style issues.
author: https://msha.ke/johnsyweb/
requirements: []
configuration:
  properties:
    pattern:
      type: string
  additionalProperties: false
